name: Export Salsify Attributes

on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Export attributes
        env:
          SAL_ORG_ID: ${{ secrets.SAL_ORG_ID }}
          SAL_API_KEY: ${{ secrets.SAL_API_KEY }}
          SAL_OUTPUT: attributes.json
        run: |
          node src/export-attributes.js
          ls -lah attributes.json

      - name: Upload attributes artifact
        uses: actions/upload-artifact@v4
        with:
          name: salsify-attributes
          path: attributes.json
